spec:
  name: sherlock-deduction-engine
  region: nyc

  services:
    # Backend service
    - name: backend
      source_dir: backend
      dockerfile_path: Dockerfile
      http_port: 5000
      instance_count: 1
      instance_size_slug: basic-xs
      routes:
        - path: /api
      envs:
        - key: DATABASE_URL
          scope: RUN_TIME
          type: SECRET
        - key: ANTHROPIC_API_KEY
          scope: RUN_TIME
          type: SECRET
      health_check:
        http_path: /api/questions

    # Frontend service
    - name: frontend
      source_dir: frontend
      dockerfile_path: Dockerfile
      http_port: 80
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /

  databases:
    - name: sherlock-db
      engine: PG
      version: "15"
      size: db-s-1vcpu-1gb
      num_nodes: 1
